DATA hints5_cycle3;
SET hints5_cycle3;
 Format
            Stratum                         $Stratum.
            APP_REGION                      $APP_REG.
            DRA                                 DRA.
            HIGHSPANLI                      HIGHSPAN.
            HISPSURNAME                     HIGHSPAN.
            HISP_HH                         HIGHSPAN.
            RUC2003                         RUC2003F.
            RUC2013                         RUC2013F.
            PR_RUCA_2010                    PR_RUCA_.
            SEC_RUCA_2010                   SEC_RUC.
            NCHSURCODE2013                  NCHSURCO.
            CENSDIV                          CENSDIV.
            CENSREG                          CENSREG.
            VAR_STRATUM                     VAR_STR.
            FormType                        FormType.
            Language_Flag                   Language.
            QDisp                              QDisp.
            UpdateDate                      Date9.
            AdultsInHH                      AdultsI.
            MailHHAdults                    MailHHA.
            SeekHealthInfo                  SeekHea.
            WhereSeekHealthInfo             WhereSe.
            WhoLookingFor                   WhoLook.
            LotOfEffort                     LotOfEf.
            Frustrated                      LotOfEf.
            ConfidentGetHealthInf           Confide.
            TrustDoctor                     TrustDo.
            TrustFamily                     TrustDo.
            TrustGov                        TrustDo.
            TrustCharities                  TrustDo.
            TrustReligiousOrgs              TrustDo.
            StrongNeedHealthInfo            StrongF.
            StrongNeedHealthInfo_OS         $StrongN.
            SeekCancerInfo                  SeekCan.
            UseInternet                     UseInte.
            Internet_DialUp                 Interne.
            Internet_BroadBnd               Interne.
            Internet_Cell                   Interne.
            Internet_WiFi                   Interne.
            InternetCancerInfoSelf          Interne.
            WhereUseInternet_Home           WhereUs.
            WhereUseInternet_Work           WhereUs.
            WhereUseInternet_PublicPlace    WhereUs.
            WhereUseInternet_MobileDevice   WhereUs.
            Electronic_SelfHealthInfo       SeekCan.
            Electronic_BuyMedicine          SeekCan.
            Electronic_TalkDoctor           SeekCan.
            Electronic_TrackedHealthCosts   SeekCan.
            Electronic_TestResults          SeekCan.
            Electronic_MadeAppts            SeekCan.
            Electronic_ECigHarms            SeekCan.
            HaveDevice_Tablet               HaveDev.
            HaveDevice_SmartPh              HaveDev.
            HaveDevice_CellPh               HaveDeF.
            HaveDevice_None                 HaveDeF.
            HaveDevice_Cat                  HaveDeG.
            TabletHealthWellnessApps        TabletH.
            Tablet_AchieveGoal              Tablet_.
            Tablet_MakeDecision             Tablet_.
            Tablet_DiscussionsHCP           Tablet_.
            WearableDevTrackHealth          Wearabl.
            FreqWearDevTrackHealth          FreqWea.
            WillingShareData_HCP            Willing.
            WillingShareData_Fam            Willing.
            OtherDevTrackHealth2            SeekCan.
            SharedHealthDeviceInfo          SharedH.
            IntRsn_VisitedSocNet            SeekCan.
            IntRsn_SharedSocNet             SeekCan.
            IntRsn_WroteBlog                SeekCan.
            IntRsn_SupportGroup             SeekCan.
            IntRsn_YouTube                  SeekCan.
            TextFromDoctor                  TextFro.
            RegularProvider                 SeekCan.
            FreqGoProvider                  FreqGoP.
            QualityCare                     Quality.
            FreqGoUrgentCare                FreqGoU.
            QualityCareUrgentCare           QualitF.
            ChanceAskQuestions              ChanceA.
            FeelingsAddressed               ChanceA.
            InvolvedDecisions               ChanceA.
            UnderstoodNextSteps             ChanceA.
            ExplainedClearly                ChanceA.
            SpentEnoughTime                 ChanceA.
            HelpUncertainty                 ChanceA.
            HealthIns_InsuranceEmp          SeekCan.
            HealthIns_InsurancePriv         SeekCan.
            HealthIns_Medicare              SeekCan.
            HealthIns_Medicaid              SeekCan.
            HealthIns_Tricare               SeekCan.
            HealthIns_VA                    SeekCan.
            HealthIns_IHS                   SeekCan.
            HealthIns_Other                 HealthF.
            HealthIns_Other_OS              $HealthI.
            HealthInsurance                 SeekCan.
            ProviderMaintainEMR2            TextFro.
            OfferedAccessHCP2               TextFro.
            OfferedAccessInsurer2           TextFro.
            AccessOnlineRecord              AccessO.
            NotAccessed_SpeakDirectly       NotAcce.
            NotAccessed_NoInternet          NotAcce.
            NotAccessed_NoNeed              NotAcce.
            NotAccessed_ConcernedPrivacy    NotAcce.
            NotAccessed_NoRecord            NotAcce.
            NotAccessed_LogInProb           NotAcce.
            NotAccessed_Uncomfortable       NotAcce.
            NotAccessed_MultipleRec         NotAcce.
            RecordsOnline_RefillMeds        Records.
            RecordsOnline_ViewResults       Records.
            RecordsOnline_RequestCorrection Records.
            RecordsOnline_MessageHCP        Records.
            RecordsOnline_DownloadHealth    Records.
            RecordsOnline_AddHealthInfo     Records.
            RecordsOnline_MakeDecision      Records.
            AccessUsingHealthApp            AccessU.
            OnlineRecClinNotes              AccessU.
            ESent_AnotherHCP                Records.
            ESent_Family                    Records.
            ESent_HealthApp                 Records.
            UnderstandOnlineMedRec          Underst.
            UsefulOnlineMedRec              UsefulO.
            Caregiving_Child                CaregiL.
            Caregiving_Spouse               CaregiL.
            Caregiving_Parent               CaregiL.
            Caregiving_AnotherFam           CaregiL.
            Caregiving_Friend               CaregiL.
            Caregiving_No                   CaregiM.
            CaregivingWho_Cat               CaregiN.
            Caregiving_Professional         CaregiF.
            Caregiving_HoursPerWeek2        Caregiv.
            Caregiving_Cancer               CaregiH.
            Caregiving_Alzheimers           CaregiH.
            Caregiving_OrthoMusc            CaregiH.
            Caregiving_MentalHealth         CaregiH.
            Caregiving_ChronicCond          CaregiH.
            Caregiving_NeuroDev             CaregiH.
            Caregiving_AcuteCond            CaregiH.
            Caregiving_Aging                CaregiH.
            Caregiving_NotSure              CaregiH.
            Caregiving_Other                CaregiI.
            Caregiving_Other_OS             $CaregiK.
            CaregivingCond_Cat              CaregiJ.
            Caregiving_AccessMedRec         CaregiG.
            GeneralHealth                   General.
            OwnAbilityTakeCareHealth        Confide.
            AvoidDoc                        AvoidDo.
            Deaf                            SeekCan.
            TalkHealthFriends               SeekCan.
            MedConditions_Diabetes          SeekCan.
            MedConditions_HighBP            SeekCan.
            MedConditions_HeartCondition    SeekCan.
            MedConditions_LungDisease       SeekCan.
            MedConditions_Depression        SeekCan.
            Height_Feet                     HeightF.
            Height_Inches                   Height_.
            Weight                           Weight.
            WeightPerception                WeightP.
            WeightIntention                 WeightI.
            LittleInterest                  LittleI.
            Hopeless                        LittleI.
            Nervous                         LittleI.
            Worrying                        LittleI.
            ChangeThinking                  ChangeT.
            ConsiderFuture                  ChangeT.
            Fruit                             Fruit.
            Vegetables                        Fruit.
            AverageCaloriesPerDay           Average.
            AverageCaloriesPerDay_DK        AveragF.
            NoticeCalorieInfoOnMenu         NoticeC.
            UnderstandCalorieInfo           UndersF.
            CalorieInfo_FewerCalories       Calorie.
            CalorieInfo_MoreCalories        Calorie.
            CalorieInfo_FewerItems          Calorie.
            CalorieInfo_SmallerSizes        Calorie.
            CalorieInfo_MoreItems           Calorie.
            CalorieInfo_LargerSizes         Calorie.
            DrinkDaysPerWeek                DrinkDa.
            DrinksPerDay                    DrinksP.
            AlcoholConditions_Cancer        Alcohol.
            AlcoholConditions_HeartDisease  Alcohol.
            AlcoholConditions_Diabetes      Alcohol.
            AlcoholConditions_LiverDisease  Alcohol.
            HCPAlcoholConsequences          HCPAlco.
            TimesModerateExercise           TimesMo.
            HowLongModerateExerciseMinutes  HowLong.
            TimesStrengthTraining           TimesSt.
            AverageTimeSitting              AveragH.
            EnjoyExercise                   EnjoyEx.
            RegExercise_Pressure            EnjoyEx.
            RegExercise_Appearance          EnjoyEx.
            RegExercise_Guilt               EnjoyEx.
            RegExercise_Enjoyment           EnjoyEx.
            GovPARec_HCP                    SeekCan.
            GovPARec_Internet               SeekCan.
            GovPARec_TV                     SeekCan.
            GovPARec_Magazine               SeekCan.
            ExRec_IncreasedEx               CaregiL.
            ExRec_DecreasedEx               CaregiL.
            ExRec_ChangedEx                 CaregiL.
            ExRec_LookedInfo                CaregiL.
            ExRec_NoChange                  CaregiL.
            ExRec_NotHeard                  CaregiL.
            ExRec_Cat                       ExRec_C.
            PhysAct_HelpSleep               PhysAct.
            PhysAct_ReduceAnxiety           PhysAct.
            PhysAct_ReducePain              PhysAct.
            AverageSleepNight               AveragG.
            AverageSleepQuality             AveragI.
            MorningNightPerson              Morning.
            SpendTimeInSunTanning           SpendTi.
            EnjoyTimeInSun                  EnjoyEx.
            TimesSunburned                  TimesSu.
            Sunburned_JobOutside            Sunburn.
            Sunburned_HomeOutside           Sunburn.
            Sunburned_Sunbathing            Sunburn.
            Sunburned_Swimming              Sunburn.
            Sunburned_Exercise              Sunburn.
            Sunburned_SportingEvent         Sunburn.
            Sunburned_OutdoorEvent          Sunburn.
            Sunburned_DayToDay              Sunburn.
            Sunburned_Other                 Sunburn.
            Sunburned_DK                    Sunburn.
            SunburnedAct_Cat                SunburH.
            Sunburned_SPF15                 Sunburn.
            Sunburned_ProtClothing          Sunburn.
            Sunburned_Shade                 Sunburn.
            Sunburned_None                  Sunburn.
            Sunburned_DontRemember          Sunburn.
            SunburnedProt_Cat               SunburG.
            Sunburned_Alcohol               SunburF.
            Smoke100                        Smoke1F.
            SmokeNow                        SmokeNo.
            TriedQuit                       TriedQu.
            ConsiderQuit                    TriedQu.
            ElectCigLessHarm                ElectCi.
            UsedECigEver                    UsedECi.
            UseECigNow                      UseECig.
            SmokeDayECig                    SmokeDa.
            NicotineWantSmoke               Nicotin.
            NicotineCauseCancer             Nicotin.
            NicotineAddictionConcern        Nicotin.
            LowNicotineHarmful              LowNicF.
            LowNicotineAddictive            LowNico.
            SeenFederalCourtTobaccoMessages2 SeenFed.
            TobaccoMessages_HESmoking       Tobacco.
            TobaccoMessages_HESecondhand    Tobacco.
            TobaccoMessages_Addictiveness   Tobacco.
            TobaccoMessages_EnhanceDelivery Tobacco.
            TobaccoMessages_LowTarLight     Tobacco.
            TobaccoMessages_Cat             TobaccF.
            GenderC                         GenderC.
            EverHadPSATest                  EverHad.
            WhenPapTest                     WhenPap.
            WhenMammogram                   WhenMam.
            EverTestedColonCa               SeekCan.
            HeardHepC                       SeekCan.
            HeardHPV                        HeardHP.
            HPVCauseCancer_Cervical         HPVCaus.
            HPVCauseCancer_Penile           HPVCaus.
            HPVCauseCancer_Anal             HPVCaus.
            HPVCauseCancer_Oral             HPVCaus.
            HeardHPVVaccine2                SeekCan.
            EverHadCancer                   EverHaF.
            CaBladder                       CaBladd.
            CaBone                          CaBladd.
            CaBreast                        CaBladd.
            CaCervical                      CaBladd.
            CaColon                         CaBladd.
            CaEndometrial                   CaBladd.
            CaHeadNeck                      CaBladd.
            CaLeukemia                      CaBladd.
            CaLiver                         CaBladd.
            CaLung                          CaBladd.
            CaHodgkins                      CaBladd.
            CaNonHodgkin                    CaBladd.
            CaMelanoma                      CaBladd.
            CaOral                          CaBladd.
            CaOvarian                       CaBladd.
            CaPancreatic                    CaBladd.
            CaPharyngeal                    CaBladd.
            CaProstate                      CaBladd.
            CaRectal                        CaBladd.
            CaRenal                         CaBladd.
            CaSkin                          CaBladd.
            CaStomach                       CaBladd.
            CaOther                         CaOther.
            CaOther_OS                      $CaOtheF.
            Cancer_Cat                      Cancer_.
            WhenDiagnosedCancer             WhenDia.
            FamilyEverHadCancer             FamilyE.
            EverythingCauseCancer           ChangeT.
            PreventNotPossible              ChangeT.
            TooManyRecommendations          ChangeT.
            CancerSign_UnexpBleeding        TextFro.
            CancerSign_BowelBladderChange   TextFro.
            CancerSign_UnexpWeightLoss      TextFro.
            InfluenceCancer_Obesity         Influen.
            InfluenceCancer_EatingFiber     Influen.
            InfluenceCancer_ProcessedMeat   Influen.
            InfluenceCancer_EatingFruitVeg  Influen.
            Age                                 Age.
            MaritalStatus                   Marital.
            Education                       Educati.
            SpeakEnglish                    SpeakEn.
            NotHisp                         NotHisp.
            Mexican                         NotHisp.
            PuertoRican                     NotHisp.
            Cuban                           NotHisp.
            OthHisp                         NotHisp.
            Hisp_Cat                        Hisp_Ca.
            White                             White.
            Black                             White.
            AmerInd                           White.
            AsInd                             White.
            Chinese                           White.
            Filipino                          White.
            Japanese                          White.
            Korean                            White.
            Vietnamese                        White.
            OthAsian                          White.
            Hawaiian                          White.
            Guamanian                         White.
            Samoan                            White.
            OthPacIsl                         White.
            Race_Cat2                       Race_Ca.
            SexualOrientation               SexualF.
            SexualOrientation_OS            $SexualO.
            TotalHousehold                  TotalHo.
            R_HHAdults                      R_HHAdul.
            HHAdults_Num                    HHAdults.
            SelfGender                      SelfGen.
            SelfAge                         SelfAge.
            SelfMOB                         SelfMOB.
            HHAdultGender2                  HHAdulM.
            HHAdultAge2                     HHAdulH.
            HHAdultMOB2                     HHAdulI.
            HHAdultGender3                  HHAdulN.
            HHAdultAge3                     HHAdult.
            HHAdultMOB3                     HHAdulJ.
            HHAdultGender4                  HHAdulO.
            HHAdultAge4                     HHAdulF.
            HHAdultMOB4                     HHAdulK.
            HHAdultGender5                  HHAdulP.
            HHAdultAge5                     HHAdulG.
            HHAdultMOB5                     HHAdulL.
            HHAdultGender6                  HHAdulA.
            HHAdultAge6                     HHAdulB.
            HHAdultMOB6                     HHAdulC.
            ChildrenInHH                    Childre.
            RentOrOwn                       RentOrO.
            IncomeRanges                    IncomeR.
            IncomeFeelings                  IncomeF.
            Prompt                          PromptF.
			IncomeRanges_IMP				IncomeR.
			AgeGrpA 						AgeGrpA.
			AgeGrpB							AgeGrpB.
			EducA							EducA.
			EducB							EducB.
			RaceEthn						RaceEthn.
			RaceEthn5						RaceEthn5f.
			HHInc							HHInc.
			BMI								BMI.
			AgeDX							AgeDX.
			TimeSinceDX						TimeSinceDX.
			smokeStat						smokeStat.
			phq4							phq4f.
			ecigUse							ecigUse.
			AvgDrinksPerWeek				AvgDrinksPerWeek.
			Treatment_H5C3					Treatment_H5C3f.
			WeeklyMinutesModerateExercise	WeeklyMinutesModerateExercise.	
			ChanceGetCancerNoDX             ChanceG.
            FreqWorryCancerNoDX             FreqWor.	
;
run;
