**Format assignments for HINTS 5 Cycle 4;
**For more information on formatting see, "How to format HINTS 5 Cycle 4 SAS Data File";

options fmtsearch=(INSERT LIBRARY NAME HERE);

DATA LIBNAME.FILENAME;
SET LIBNAME.hints5_cycle4_public;
  Format
            Stratum                          $Stratum.
            APP_REGION                       $APP_REG.
            DRA                                  DRA.
            HIGHSPANLI                       HIGHSPAN.
            HISPSURNAME                      HIGHSPAN.
            HISP_HH                          HIGHSPAN.
            Treatment_H5C4                   Treatmen.
            RUC2013                          RUCA2013R.
            PR_RUCA_2010                     PR_RUCAR.
            NCHSURCODE2013                   NCHSURCO.
            CENSDIV                           CENSDIV.
            CENSREG                           CENSREG.
            VAR_STRATUM                      $VAR_STR.
            Language_Flag                    Language.
            QDisp                               QDisp.
			UpdateDate						 date9.
            Pandemic                         Pandemi.
            AdultsInHH                       AdultsI.
            MailHHAdults                     MailHHA.
            SeekCancerInfo                   SeekCan.
            CancerLotOfEffort                CancerL.
            CancerFrustrated                 CancerL.
            CancerConfidentGetHealthInf      CancerC.
            CancerTrustDoctor                CancerT.
            CancerTrustFamily                CancerT.
            CancerTrustGov                   CancerT.
            CancerTrustCharities             CancerT.
            CancerTrustReligiousOrgs         CancerT.
            StrongNeedCancerInfo             StrongF.
            StrongNeedCancerInfo_OS          $StrongN.
            UseInternet                      UseInte.
            Internet_DialUp                  Interne.
            Internet_BroadBnd                Interne.
            Internet_Cell                    Interne.
            Internet_WiFi                    Interne.
            WhereUseInternet_Home            WhereUs.
            WhereUseInternet_Work            WhereUs.
            WhereUseInternet_PublicPlace     WhereUs.
            WhereUseInternet_MobileDevice    WhereUs.
            InternetSpeed                    InternF.
            Electronic_SelfHealthInfo        Electro.
            Electronic_TalkDoctor            Electro.
            Electronic_TestResults           Electro.
            Electronic_MadeAppts             Electro.
            HaveDevice_Tablet                HaveDev.
            HaveDevice_SmartPh               HaveDev.
            HaveDevice_CellPh                HaveDeF.
            HaveDevice_None                  HaveDeF.
            HaveDevice_Cat                   HaveDeG.
            TabletHealthWellnessApps         TabletH.
            UsedHealthWellnessApps           UsedHea.
            Tablet_AchieveGoal               Tablet_.
            Tablet_MakeDecision              Tablet_.
            Tablet_DiscussionsHCP            Tablet_.
            WearableDevTrackHealth           Wearabl.
            FreqWearDevTrackHealth           FreqWea.
            WillingShareData_HCP             Willing.
            WillingShareData_YourFamily      Willing.
            WillingShareData_YourFriends     Willing.
            SharedHealthDeviceInfo           SharedH.
            IntRsn_VisitedSocNet             Electro.
            IntRsn_SharedSocNet              Electro.
            IntRsn_SupportGroup              Electro.
            IntRsn_YouTube                   Electro.
            RegularProvider                  Electro.
            FreqGoProvider                   FreqGoP.
            QualityCare                      Quality.
            ChanceAskQuestions               ChanceA.
            FeelingsAddressed                ChanceA.
            InvolvedDecisions                ChanceA.
            UnderstoodNextSteps              ChanceA.
            ExplainedClearly                 ChanceA.
            SpentEnoughTime                  ChanceA.
            HelpUncertainty                  ChanceA.
            ProbCare_BringTest               ProbCar.
            ProbCare_WaitLong                ProbCar.
            ProbCare_RedoTest                ProbCar.
            ProbCare_ProvideHist             ProbCar.
            HealthIns_InsuranceEmp           Electro.
            HealthIns_InsurancePriv          Electro.
            HealthIns_Medicare               Electro.
            HealthIns_Medicaid               Electro.
            HealthIns_Tricare                Electro.
            HealthIns_VA                     Electro.
            HealthIns_IHS                    Electro.
            HealthIns_Other                  HealthF.
            HealthIns_Other_OS               $HealthI.
            HealthInsurance                  Electro.
            ProviderMaintainEMR2             Provide.
            OfferedAccessHCP2                Provide.
            OfferedAccessInsurer2            Provide.
            HCPEncourageOnlineRec            HCPEnco.
            AccessOnlineRecord               AccessO.
            NotAccessed_SpeakDirectly        NotAcce.
            NotAccessed_NoInternet           NotAcce.
            NotAccessed_NoNeed               NotAcce.
            NotAccessed_ConcernedPrivacy     NotAcce.
            NotAccessed_NoRecord             NotAcce.
            NotAccessed_LogInProb            NotAcce.
            NotAccessed_Uncomfortable        NotAcce.
            NotAccessed_MultipleRec          NotAcce.
            RecordsOnline_ViewResults        Records.
            RecordsOnline_MessageHCP         Records.
            RecordsOnline_DownloadHealth     Records.
            HowAccessOnlineRecord            HowAcce.
            OnlineRecClinNotes               OnlineR.
            ESent_AnotherHCP                 Records.
            ESent_Family                     Records.
            ESent_HealthApp                  Records.
            UnderstandOnlineMedRec           Underst.
            Caregiving_Child                 HaveDev.
            Caregiving_Spouse                HaveDev.
            Caregiving_Parent                HaveDev.
            Caregiving_AnotherFam            HaveDev.
            Caregiving_Friend                HaveDev.
            Caregiving_No                    CaregiK.
            CaregivingWho_Cat                CaregiL.
            Caregiving_Professional          Caregiv.
            Caregiving_Cancer                CaregiG.
            Caregiving_Alzheimers            CaregiG.
            Caregiving_OrthoMusc             CaregiG.
            Caregiving_MentalHealth          CaregiG.
            Caregiving_ChronicCond           CaregiG.
            Caregiving_NeuroDev              CaregiG.
            Caregiving_AcuteCond             CaregiG.
            Caregiving_Aging                 CaregiG.
            Caregiving_Other                 CaregiH.
            Caregiving_Other_OS              $CaregiJ.
            Caregiving_NotSure               CaregiG.
            CaregivingCond_Cat               CaregiI.
            Caregiving_AccessMedRec2         CaregiF.
            HeardGenTest_Ancestry            HeardGF.
            HeardGenTest_HealthRisk          HeardGF.
            HeardGenTest_CancerRisk          HeardGF.
            HeardGenTest_Other               HeardGF.
            HeardGenTest_Other_OS            $HeardGe.
            HeardGenTest_NotSure             HeardGF.
            HeardGenTest_None                HeardGG.
            HeardGenTest_Cat                 HeardGH.
            TestSource_Ppr                   TestSou.
            TestSource_Mag                   TestSou.
            TestSource_Radio                 TestSou.
            TestSource_HCP                   TestSou.
            TestSource_Counselor             TestSou.
            TestSource_Family                TestSou.
            TestSource_Friend                TestSou.
            TestSource_SocMed                TestSou.
            TestSource_TV                    TestSou.
            TestSource_Www                   TestSou.
            TestSource_Other                 TestSou.
            TestSource_Other_OS              $TestSoF.
            TestSource_NotHeard              TestSou.
            TestSource_NotSure               TestSou.
            TestSource_Cat                   TestSoG.
            HadTest2_Ancestry                TestSou.
            HadTest2_HealthRisk              TestSou.
            HadTest2_CancerRisk              TestSou.
            HadTest2_Other                   TestSou.
            HadTest2_Other_OS                $HadTesG.
            HadTest2_NotSure                 TestSou.
            HadTest2_None                    HadTest.
            HadTest2_Cat                     HadTesF.
            SharedRes2_HCP                   SharedR.
            SharedRes2_Counselor             SharedR.
            SharedRes2_Spouse                SharedR.
            SharedRes2_Parent                SharedR.
            SharedRes2_Sibling               SharedR.
            SharedRes2_Child                 SharedR.
            SharedRes2_Friend                SharedR.
            SharedRes2_Other                 SharedR.
            SharedRes2_NotShared             SharedR.
            SharedRes2_Cat                   SharedF.
            UndGenTest_HCP                   SharedR.
            UndGenTest_Counselor             SharedR.
            UndGenTest_Spouse                SharedR.
            UndGenTest_Parent                SharedR.
            UndGenTest_Sibling               SharedR.
            UndGenTest_Child                 SharedR.
            UndGenTest_Friend                SharedR.
            UndGenTest_Other                 SharedR.
            UndGenTest_NoOne                 SharedR.
            UndGenTest_Cat                   UndGenT.
            Genetics2_Obesity                Genetic.
            Genetics2_Cancer                 Genetic.
            Genetics2_Cardio                 Genetic.
            Genetics2_Diabetes               Genetic.
            KnowGenes_PreventCa              KnowGen.
            KnowGenes_DetectCa               KnowGen.
            KnowGenes_TreatCa                KnowGen.
            ClinicalTrialKnowledge           ClinicF.
            ClinTrial_HelpingPeople          ClinTri.
            ClinTrial_GetPaid                ClinTri.
            ClinTrial_GetSupport             ClinTri.
            ClinTrial_DocEncouraged          ClinTri.
            ClinTrial_FamEncouraged          ClinTri.
            ClinTrial_GetBetter              ClinTri.
            ClinTrial_NewCare                ClinTri.
            ClinTrial_StdNotCovered          ClinTri.
            FirstInfoClinTrials              FirstIn.
            TrustInfoClinTrials              TrustIn.
            HeardClinTrialsWebsite           Electro.
            InvitedClinTrial                 Invited.
            ParticipatedClinTrial            Partici.
            GeneralHealth                    General.
            OwnAbilityTakeCareHealth         CancerC.
            Deaf                             Electro.
            TalkHealthFriends                Electro.
            MedConditions_Diabetes           Electro.
            MedConditions_HighBP             Electro.
            MedConditions_HeartCondition     Electro.
            MedConditions_LungDisease        Electro.
            MedConditions_Depression         Electro.
            Height_Feet                      HeightF.
            Height_Inches                    Height_.
            Weight                            Weight.
            LittleInterest                   LittleI.
            Hopeless                         LittleI.
            Nervous                          LittleI.
            Worrying                         LittleI.
            Threatened_Values                Threate.
            Threatened_Strengths             Threate.
            ExpectWorst                      ExpectW.
            MostImportantValues              MostImp.
            NoticeCalorieInfoOnMenu          Electro.
            JunkFoodAdRestrictions           JunkFoo.
            DrinkDaysPerWeek                 DrinkDa.
            DrinksPerDay                     DrinksP.
            DrinksOneOccasion                DrinksO.
            Beer_CancerRisk                  Beer_Ca.
            Wine_CancerRisk                  Beer_Ca.
            Liquor_CancerRisk                Beer_Ca.
            Beer_HeartRisk                   Beer_Ca.
            Wine_HeartRisk                   Beer_Ca.
            Liquor_HeartRisk                 Beer_Ca.
            ExcessiveAlcohol_BanAds          Excessi.
            ExcessiveAlcohol_ReqWarn         Excessi.
            ExcessiveAlcohol_Guidelines      Excessi.
            TimesModerateExercise            TimesMo.
            HowLongModerateExerciseMinutes   HowLong.
            TimesStrengthTraining            TimesSt.
            AverageTimeSitting               Average.
            Smoke100                         Smoke1F.
            SmokeNow                         SmokeNo.
            ElectCigLessHarm                 ElectCi.
            UsedECigEver                     UsedECi.
            UseECigNow                       UseECig.
            HeardHeatedTobacco               HeardHe.
            SeenFederalCourtTobaccoMessages2 SeenFed.
            TobaccoMessages_HESmoking        Tobacco.
            TobaccoMessages_HESecondhand     Tobacco.
            TobaccoMessages_Addictiveness    Tobacco.
            TobaccoMessages_EnhanceDelivery  Tobacco.
            TobaccoMessages_LowTarLight      Tobacco.
            TobaccoMessages_Cat              TobaccF.
            CigMeasures_MovieRatings         Excessi.
            CigMeasures_WarningLabels        Excessi.
            TobaccoMeasures_HideProducts     Excessi.
            TobaccoMeasures_HideAds          Excessi.
            TobaccoMeasures_NoSocMed         Excessi.
            HeardPrecisionMedicine           Electro.
            DrTalkLungTest                   DrTalkL.
            WhenPapTest                      WhenPap.
            WhenMammogram                    WhenMam.
            EverTestedColonCa                Electro.
            HeardHPV                         HeardHP.
            HPVCauseCancer_Cervical          HPVCaus.
            HPVCauseCancer_Penile            HPVCaus.
            HPVCauseCancer_Anal              HPVCaus.
            HPVCauseCancer_Oral              HPVCaus.
            HeardHPVVaccine2                 Electro.
            FreqWorryCancer                  FreqWor.
            EverythingCauseCancer            Threate.
            PreventNotPossible               Threate.
            TooManyRecommendations           Threate.
            HighRiskChangeBehavior           Threate.
            GeneticChangeIncreasedRisk       ClinTri.
            InfluenceCancer_Obesity          CaInflu.
            InfluenceCancer_AdultWeight      CaInflu.
            InfluenceCancer_RedMeat          CaInflu.
            EverHadCancer                    EverHad.
            CaBladder                        CaBladd.
            CaBone                           CaBladd.
            CaBreast                         CaBladd.
            CaCervical                       CaBladd.
            CaColon                          CaBladd.
            CaEndometrial                    CaBladd.
            CaHeadNeck                       CaBladd.
            CaLeukemia                       CaBladd.
            CaLiver                          CaBladd.
            CaLung                           CaBladd.
            CaHodgkins                       CaBladd.
            CaNonHodgkin                     CaBladd.
            CaMelanoma                       CaBladd.
            CaOral                           CaBladd.
            CaOvarian                        CaBladd.
            CaPancreatic                     CaBladd.
            CaPharyngeal                     CaBladd.
            CaProstate                       CaBladd.
            CaRectal                         CaBladd.
            CaRenal                          CaBladd.
            CaSkin                           CaBladd.
            CaStomach                        CaBladd.
            CaOther                          CaOther.
            CaOther_OS                       $CaOtheF.
            Cancer_Cat                       Cancer_.
            WhenDiagnosedCancer              WhenDia.
            DiscussedClinicalTrial           Discuss.
            ClinicalTrialCancerTx2           Clinica.
            FamiliarFamilyCancer2            Familia.
            FamilyEverHadCancer2             FamilyE.
            Age                                  Age. 
            BirthGender                      BirthGe.
            WorkFulltime                     HCPEnco.
            Occupation_Employed              HaveDev.
            Occupation_1YUnemployed          HaveDev.
            Occupation_Less1YUnemployed      HaveDev.
            Occupation_Homemaker             HaveDev.
            Occupation_Student               HaveDev.
            Occupation_Retired               HaveDev.
            Occupation_Disabled              HaveDev.
            Occupation_Other                 OccupaF.
            Occupation_Other_OS              $Occupat.
            Occupation_Cat                   OccupaG.
            FullTimeOcc_Cat                  FullTim.
            MaritalStatus                    Marital.
            Education                        Educati.
            NotHisp                          HaveDev.
            Mexican                          HaveDev.
            PuertoRican                      HaveDev.
            Cuban                            HaveDev.
            OthHisp                          HaveDev.
            Hisp_Cat                         Hisp_Ca.
            White                              White.
            Black                              White.
            AmerInd                            White.
            AsInd                              White.
            Chinese                            White.
            Filipino                           White.
            OthAsian                           White.
            OthPacIsl                          White.
            Race_Cat2                        Race_Ca.
            EthnicGroupBelonging             ExpectW.
            SexualOrientation                SexualF.
            SexualOrientation_OS             $SexualO.
            TotalHousehold                   TotalHo.
            R_HHAdults                       R_HHAdul.
            HHAdults_Num                     HHAdults.
            SelfGender                       BirthGe.
            SelfAge                          SelfAge.
            SelfMOB                          SelfMOB.
            HHAdultGender2                   HHAdulM.
            HHAdultAge2                      HHAdulH.
            HHAdultMOB2                      HHAdulI.
            HHAdultGender3                   HHAdulN.
            HHAdultAge3                      HHAdult.
            HHAdultMOB3                      HHAdulJ.
            HHAdultGender4                   HHAdulO.
            HHAdultAge4                      HHAdulF.
            HHAdultMOB4                      HHAdulK.
            HHAdultGender5                   HHAdulP.
            HHAdultAge5                      HHAdulG.
            HHAdultMOB5                      HHAdulL.
            ChildrenInHH                     Childre.
            PoliticalViewPoint               Politic.
            IncomeRanges                     IncomeR.
            IncomeFeelings                   IncomeF.

			AgeGrpA 						AgeGrpA.
			AgeGrpB 						AgeGrpB.
			EducA 							EducA.
			EducB 							EducB.
			RaceEthn 						RaceEthn.
			HHInc 							HHInc.
			BMI 							BMI.
			AgeDX 							AgeDX.
			TimeSinceDX 					TimeSinceDX.
			smokeStat 						smokeStat.
			RaceEthn5 						RaceEthn5f.
			phq4 							phq4f.
			WeeklyMinutesModerateExercise  	WeeklyMinutesModerateExercise.
            IncomeRanges_IMP  				incomer.
			ECigUse 						ECigStat.
			AvgDrinksPerWeek 				AvgDrinksPerWeek.
			PCCScale                        pccscale.
        ;
run;
