DATA hints5_cycle2;
SET hints5_cycle2;
  format 

            Stratum                         $Stratum.
            APP_REGION                      $APP_REG.
            HIGHSPANLI                      HIGHSPAN.
            HISPSURNAME                     HIGHSPAN.
            HISP_HH                         HIGHSPAN.
            RUC2003                         RUC2003F.
            RUC2013                         RUC2013F.
            PR_RUCA_2010                    PR_RUCA_.
            SEC_RUCA_2010                   SEC_RUC.
            NCHSURCODE2013                  NCHSURCO.
            CENSDIV                          CENSDIV.
            CENSREG                          CENSREG.
            VAR_STRATUM                     $VAR_STR.
            FormType                        FormType.
            Language_Flag                   Language.
            QDisp                              QDisp.
            UpdateDate                      Date9.
            AdultsInHH                      AdultsI.
            MailHHAdults                    MailHHA.
            SeekHealthInfo                  SeekHea.
            WhereSeekHealthInfo             WhereSe.
            WhoLookingFor                   WhoLook.
            SeekCancerInfo                  SeekCan.
            CancerLotOfEffort               CancerL.
            CancerFrustrated                CancerL.
            CancerConcernedQuality          CancerL.
            CancerTooHardUnderstand         CancerL.
            CancerConfidentGetHealthInf     CancerC.
            CancerTrustDoctor               CancerT.
            CancerTrustFamily               CancerT.
            CancerTrustNewsMag              CancerT.
            CancerTrustRadio                CancerT.
            CancerTrustInternet             CancerT.
            CancerTrustTelevision           CancerT.
            CancerTrustGov                  CancerT.
            CancerTrustCharities            CancerT.
            CancerTrustReligiousOrgs        CancerT.
            StrongNeedCancerInfo            StrongF.
            StrongNeedCancerInfo_OS         $StrongN.
            UseInternet                     UseInte.
            Internet_DialUp                 Interne.
            Internet_Broadbnd               Interne.
            Internet_Cell                   Interne.
            Internet_WiFi                   Interne.
            InternetCancerInfoSelf          InternF.
            WhereUseInternet_Home           WhereUs.
            WhereUseInternet_Work           WhereUs.
            WhereUseInternet_PublicPlace    WhereUs.
            WhereUseInternet_MobileDevice   WhereUs.
            Electronic_SelfHealthInfo       InternF.
            Electronic_HealthInfoSE         InternF.
            Electronic_BuyMedicine          InternF.
            Electronic_LookedAssistance     InternF.
            Electronic_TalkDoctor           InternF.
            Electronic_TrackedHealthCosts   InternF.
            Electronic_TestResults          InternF.
            HaveDevice_Tablet               HaveDev.
            HaveDevice_SmartPh              HaveDev.
            HaveDevice_CellPh               HaveDeF.
            HaveDevice_None                 HaveDeF.
            HaveDevice_Cat                  HaveDeG.
            TabletHealthWellnessApps        TabletH.
            Tablet_AchieveGoal              Tablet_.
            Tablet_MakeDecision             Tablet_.
            Tablet_DiscussionsHCP           Tablet_.
            OtherDevTrackHealth             InternF.
            SharedHealthDeviceInfo          SharedH.
            IntRsn_VisitedSocNet            InternF.
            IntRsn_SharedSocNet             InternF.
            IntRsn_WroteBlog                InternF.
            IntRsn_SupportGroup             InternF.
            IntRsn_YouTube                  InternF.
            TextFromDoctor                  TextFro.
            RegularProvider                 InternF.
            MostRecentCheckup2              MostRec.
            FreqGoProvider                  FreqGoP.
            ChanceAskQuestions              ChanceA.
            FeelingsAddressed               ChanceA.
            InvolvedDecisions               ChanceA.
            UnderstoodNextSteps             ChanceA.
            ExplainedClearly                ChanceA.
            SpentEnoughTime                 ChanceA.
            HelpUncertainty                 ChanceA.
            QualityCare                     Quality.
            ProbCare_BringTest              ProbCar.
            ProbCare_WaitLong               ProbCar.
            ProbCare_RedoTest               ProbCar.
            ProbCare_ProvideHist            ProbCar.
            HealthIns_InsuranceEmp          InternF.
            HealthIns_InsurancePriv         InternF.
            HealthIns_Medicare              InternF.
            HealthIns_Medicaid              InternF.
            HealthIns_Tricare               InternF.
            HealthIns_VA                    InternF.
            HealthIns_IHS                   InternF.
            HealthIns_Other                 HealthF.
            HealthIns_Other_OS              $HealthI.
            HealthInsurance                 InternF.
            ProviderMaintainEMR2            TextFro.
            ConfidentInfoSafe               Confide.
            WithheldInfoPrivacy             InternF.
            EverOfferedAccessRec            EverOff.
            WhoOffered_HCP                  WhoOffe.
            WhoOffered_Insurer              WhoOffe.
            WhoOffered_Other                WhoOffF.
            WhoOffered_Other_OS             $WhoOffH.
            WhoOffered_Cat                  WhoOffG.
            AccessOnlineRecord              AccessO.
            NotAccessed_SpeakDirectly       NotAcce.
            NotAccessed_NoInternet          NotAcce.
            NotAccessed_NoNeed              NotAcce.
            NotAccessed_ConcernedPrivacy    NotAcce.
            NotAccessed_NoRecord            NotAcce.
            NotAccessed_Other               NotAccF.
            NotAccessed_Other_OS            $NotAccG.
            RecordsOnline_RefillMeds        RecordF.
            RecordsOnline_Paperwork         RecordF.
            RecordsOnline_RequestCorrection RecordF.
            RecordsOnline_MessageHCP        RecordF.
            RecordsOnline_DownloadHealth    RecordF.
            RecordsOnline_AddHealthInfo     RecordF.
            RecordsOnline_MakeDecision      RecordF.
            RecordsOnline_HealthProbs       Records.
            RecordsOnline_Allergies         Records.
            RecordsOnline_VisitSummary      Records.
            RecordsOnline_ClinNotes         Records.
            RecordsOnline_Immunizations     Records.
            ESent_AnotherHCP                RecordF.
            ESent_Family                    RecordF.
            ESent_HealthApp                 RecordF.
            UsefulOnlineMedRec              UsefulO.
            Caregiving_Child                CaregiQ.
            Caregiving_Spouse               CaregiQ.
            Caregiving_Parent               CaregiQ.
            Caregiving_AnotherFam           CaregiQ.
            Caregiving_Friend               CaregiQ.
            Caregiving_No                   CaregiR.
            CaregivingWho_Cat               CaregiT.
            Caregiving_Professional         CaregiF.
            Caregiving_Cancer               CaregiK.
            Caregiving_Alzheimers           CaregiK.
            Caregiving_OrthoMusc            CaregiK.
            Caregiving_MentalHealth         CaregiK.
            Caregiving_ChronicCond          CaregiK.
            Caregiving_NeuroDev             CaregiK.
            Caregiving_AcuteCond            CaregiK.
            Caregiving_Aging                CaregiK.
            Caregiving_NotSure              CaregiK.
            Caregiving_Other                CaregiL.
            Caregiving_Other_OS             $CaregiP.
            CaregivingCond_Cat              CaregiO.
            Caregiving_HoursPerWeek2        CaregiJ.
            Caregiving_HowLong              CaregiI.
            Caregiving_Reside               CaregiH.
            Caregiving_BedsChairs           CaregiK.
            Caregiving_Dressing             CaregiK.
            Caregiving_Toilet               CaregiK.
            Caregiving_Incontinence         CaregiK.
            Caregiving_Bathing              CaregiK.
            Caregiving_MealPrep             CaregiK.
            Caregiving_Feeding              CaregiK.
            Caregiving_Finances             CaregiK.
            Caregiving_Shopping             CaregiK.
            Caregiving_Housework            CaregiK.
            Caregiving_Transportation       CaregiK.
            CaregivingActivities_Cat        CaregiN.
            Caregiving_MedTasks             CaregiK.
            Caregiving_CommunicateHCP       CaregiK.
            Caregiving_ArrangeSvcs          CaregiK.
            Caregiving_SpendTime            CaregiK.
            CaregivingMedAct_Cat            CaregiM.
            Caregiving_AccessMedRec         Caregiv.
            Caregiver_MedTrain              CaregiG.
            Caregiver_AccessHelp            CaregiG.
            Caregiver_RespiteCare           CaregiG.
            Caregiver_SupportGroup          CaregiG.
            Caregiver_Counseling            CaregiG.
            CaregiverTraining_InPerson      CaregiQ.
            CaregiverTraining_Hotline       CaregiQ.
            CaregiverTraining_ReadingMat    CaregiQ.
            CaregiverTraining_OnlineVideo   CaregiQ.
            CaregiverTraining_Virtual       CaregiQ.
            CaregiverTraining_Cat           CaregiS.
            KnowledgePalliativeCare         Knowled.
            PCGoal_HelpFamCope              PCGoal_.
            PCGoal_SocEmotSupport           PCGoal_.
            PCGoal_ManageSymptoms           PCGoal_.
            PCGoal_MoreTime                 PCGoal_.
            PCStrongNeedInfo                PCStron.
            PCTrustInfo                     PCStron.
            PCMeansGivingUp                 PCGoal_.
            PCObligatedToInform             PCGoal_.
            PCStopTreatments                PCGoal_.
            PCHospiceCare                   PCGoal_.
            PCThinkDeath                    PCGoal_.
            GeneralHealth                   General.
            OwnAbilityTakeCareHealth        CancerC.
            MedConditions_Diabetes          InternF.
            MedConditions_HighBP            InternF.
            MedConditions_HeartCondition    InternF.
            MedConditions_LungDisease       InternF.
            MedConditions_Arthritis         InternF.
            MedConditions_Depression        InternF.
            Height_Feet                     HeightF.
            Height_Inches                   Height_.
            Weight                           Weight.
            LittleInterest                  LittleI.
            Hopeless                        LittleI.
            Nervous                         LittleI.
            Worrying                        LittleI.
            EmotionalSupport2               Emotion.
            TalkHealthFriends2              Emotion.
            HelpPreparingMeals              Emotion.
            HelpTransportDoctor             Emotion.
            HelpDailyChores2                Emotion.
            HelpRunErrands                  Emotion.
            Deaf                            InternF.
            InfluenceCancer_Obesity         Influen.
            InfluenceCancer_EatingHealthy   Influen.
            InfluenceCancer_RegExercise     Influen.
            NoticeCalorieInfoOnMenu         NoticeC.
            UnderstandCalorieInfo           Underst.
            CalorieInfo_FewerCalories       Calorie.
            CalorieInfo_MoreCalories        Calorie.
            CalorieInfo_FewerItems          Calorie.
            CalorieInfo_SmallerSizes        Calorie.
            CalorieInfo_MoreItems           Calorie.
            CalorieInfo_LargerSizes         Calorie.
            AverageCaloriesPerDay           Average.
            AverageCaloriesPerDay_DK        AveraDK.
            DrinkDaysPerWeek                DrinkDa.
            DrinksPerDay                    DrinksP.
            TimesModerateExercise           TimesMo.
            HowLongModerateExerciseMinutes  HowLong.
            TimesStrengthTraining           TimesSt.
            AverageTimeSitting              AveragF.
            TimesUsedTanningBed             TimesUs.
            SpendTimeInSunTanning           SpendTi.
            HCPAdvisedLimitingSun           InternF.
            SunEffectAfter1Hour             SunEffe.
            Smoke100                        Smoke1F.
            SmokeNow                        SmokeNo.
            ElectCigLessHarm                ElectCi.
            UsedECigEver                    UsedECi.
            UseECigNow                      UseECig.
            SeenFederalCourtTobaccoMessages SeenFed.
            TobaccoMessages_HESmoking       Tobacco.
            TobaccoMessages_HESecondhand    Tobacco.
            TobaccoMessages_Addictiveness   Tobacco.
            TobaccoMessages_EnhanceDelivery Tobacco.
            TobaccoMessages_LowTarLight     Tobacco.
            TobaccoMessages_Cat             TobaccF.
            GenderC                         GenderC.
            WhenPapTest                     WhenPap.
            WhenMammogram                   WhenMam.
            EverTestedColonCa               InternF.
            HeardHPV                        HeardHP.
            HPVCauseCancer_Cervical         HPVCaus.
            HPVCauseCancer_Penile           HPVCaus.
            HPVCauseCancer_Anal             HPVCaus.
            HPVCauseCancer_Oral             HPVCaus.
            HeardHPVVaccine2                InternF.
            FamBetween9and27                FamBetw.
            RecommendHPVShot                Recomme.
            EverHadCancer                   EverHad.
            CaBladder                       CaBladd.
            CaBone                          CaBladd.
            CaBreast                        CaBladd.
            CaCervical                      CaBladd.
            CaColon                         CaBladd.
            CaEndometrial                   CaBladd.
            CaHeadNeck                      CaBladd.
            CaLeukemia                      CaBladd.
            CaLiver                         CaBladd.
            CaLung                          CaBladd.
            CaHodgkins                      CaBladd.
            CaNonHodgkin                    CaBladd.
            CaMelanoma                      CaBladd.
            CaOral                          CaBladd.
            CaOvarian                       CaBladd.
            CaPancreatic                    CaBladd.
            CaPharyngeal                    CaBladd.
            CaProstate                      CaBladd.
            CaRectal                        CaBladd.
            CaRenal                         CaBladd.
            CaSkin                          CaBladd.
            CaStomach                       CaBladd.
            CaOther                         CaOther.
            CaOther_OS                      $CaOtheF.
            Cancer_Cat                      Cancer_.
            WhenDiagnosedCancer             WhenDia.
            FreqWorryCancerAgain            FreqWoF.
            ImagineCancerAgain              ImaginF.
            FreqWorryCancerNoDx             FreqWor.
            ImagineCancer                   Imagine.
            EverythingCauseCancer           Everyth.
            PreventNotPossible              Everyth.
            TooManyRecommendations          Everyth.
            FamiliarFamilyCancer            Familia.
            FamilyCancer_Mother             FamilyC.
            FamilyCancer_Father             FamilyC.
            FamilyCancer_Sister             FamilyC.
            FamilyCancer_Brother            FamilyC.
            FamilyCancer_Children           FamilyC.
            FamilyCancer_OthFam             FamilyC.
            FamilyCancer_HCP                FamilyC.
            FamilyCancer_None               FamilyC.
            FamilyCancer_Cat                FamilyF.
            ConfidentFamilyHistory          CancerC.
            FamilyEverHadCancer             FamilyE.
            Age                                 Age.
            OccupationStatus                OccupaF.
            OccupationStatus_OS             $Occupat.
            Employed                        Employe.
            Unemployed                      Employe.
            Homemaker                       Employe.
            Student                         Employe.
            Retired                         Employe.
            Disabled                        Employe.
            OtherOcc                        Employe.
            MultiOcc                        MultiOc.
            ActiveDutyArmedForces           ActiveD.
            ReceivedCareVA                  Receive.
            MaritalStatus                   Marital.
            Education                       Educati.
            BornInUSA                       BornInU.
            YearCameToUSA                   YearCam.
            SpeakEnglish                    SpeakEn.
            NotHisp                         FamilyC.
            Mexican                         FamilyC.
            PuertoRican                     FamilyC.
            Cuban                           FamilyC.
            OthHisp                         FamilyC.
            Hisp_Cat                        Hisp_Ca.
            White                             White.
            Black                             White.
            AmerInd                           White.
            AsInd                             White.
            Chinese                           White.
            Filipino                          White.
            Japanese                          White.
            Korean                            White.
            Vietnamese                        White.
            OthAsian                          White.
            Hawaiian                          White.
            Guamanian                         White.
            Samoan                            White.
            OthPacIsl                         White.
            Race_Cat2                       Race_Ca.
            SexualOrientation               SexualF.
            SexualOrientation_OS            $SexualO.
            TotalHousehold                  TotalHo.
            R_HHAdults                      R_HHAdul.
            HHAdults_Num                    HHAdults.
            SelfGender                      SelfGen.
            SelfAge                         SelfAge.
            SelfMOB                         SelfMOB.
            HHAdultGender2                  HHAdulM.
            HHAdultAge2                     HHAdult.
            HHAdultMOB2                     HHAdulI.
            HHAdultGender3                  HHAdulN.
            HHAdultAge3                     HHAdulF.
            HHAdultMOB3                     HHAdulJ.
            HHAdultGender4                  HHAdulO.
            HHAdultAge4                     HHAdulG.
            HHAdultMOB4                     HHAdulK.
            HHAdultGender5                  HHAdulP.
            HHAdultAge5                     HHAdulH.
            HHAdultMOB5                     HHAdulL.
            ChildrenInHH                    Childre.
            RentOrOwn                       RentOrO.
            IncomeRanges                    IncomeR.
            MailSurveyTimeMin               MailSuF.
            MailSurveyTimeHrs               MailSur.
            TypeOfAddressA                  TypeOfA.
            TypeOfAddressB                  TypeOfA.
            TypeOfAddressC                  TypeOfA.
            TypeOfAddressD                  TypeOfA.

			AgeGrpA 						AgeGrpA.
			AgeGrpB 						AgeGrpB.
			EducA 							EducA.
			EducB 							EducB.
			RaceEthn 						RaceEthn.
			HHInc 							HHInc.
			BMI 							BMI.
			AgeDX 							AgeDX.
			TimeSinceDX 					TimeSinceDX.
			smokeStat 						smokeStat.
			RaceEthn5 						RaceEthn5f.
			phq4 							phq4f.
			WeeklyMinutesModerateExercise  	WeeklyMinutesModerateExercise.
            IncomeRanges_IMP  				incomer.
			ECigUse 						ECigStat.
			AvgDrinksPerWeek 				AvgDrinksPerWeek.
        ;
run;
