DATA hints5_cycle1;
SET hints5_cycle1;
format

            Stratum                         $Stratum.
            APP_REGION                      $APP_REG.
            HIGHSPANLI                      HIGHSPAN.
            HISPSURNAME                     HIGHSPAN.
            HISP_HH                         HIGHSPAN.
            RUC2003                         RUC2003F.
            RUC2013                         RUC2013F.
            PR_RUCA_2010                    PR_RUCAF.
            SEC_RUCA_2010                   SEC_RUC.
            NCHSURCODE2013                  NCHSURCO.
            CENSDIV                         CENSDIV.
            CENSREG                          CENSREG.
            FormType                        FormType.
            Language_Flag                   Language.
            QDisp                              QDisp.
            UpdateDate                      Date9.
            AdultsInHH                      AdultsI.
            MailHHAdults                    MailHHA.
            SeekHealthInfo                  SeekHea.
            WhereSeekHealthInfo             WhereSe.
            WhoLookingFor                   WhoLook.
            LotOfEffort                     LotOfEf.
            Frustrated                      LotOfEf.
            ConcernedQuality                LotOfEf.
            TooHardUnderstand               LotOfEf.
            ConfidentGetHealthInf           ConfidF.
            TrustDoctor                     TrustDo.
            TrustFamily                     TrustDo.
            TrustNewsMag                    TrustDo.
            TrustRadio                      TrustDo.
            TrustInternet                   TrustDo.
            TrustTelevision                 TrustDo.
            TrustGov                        TrustDo.
            TrustCharities                  TrustDo.
            TrustReligiousOrgs              TrustDo.
            StrongNeedHealthInfo            StrongG.
            StrongNeedHealthInfo_OS         $StrongN.
            SeekCancerInfo                  SeekCan.
            InternetCancerInfoSelf          SeekCan.
            UseInternet                     UseInte.
            Internet_DialUp                 Interne.
            Internet_BroadBnd               Interne.
            Internet_Cell                   Interne.
            Internet_WiFi                   Interne.
            WhereUseInternet_Home           WhereUs.
            WhereUseInternet_Work           WhereUs.
            WhereUseInternet_School         WhereUs.
            WhereUseInternet_PublicPlace    WhereUs.
            WhereUseInternet_MobileDevice   WhereUs.
            WhereUseInternet_GamingDevice   WhereUs.
            Electronic_SelfHealthInfo       SeekCan.
            Electronic_HealthInfoSE         SeekCan.
            Electronic_BuyMedicine          SeekCan.
            Electronic_HCPSearch            SeekCan.
            Electronic_TalkDoctor           SeekCan.
            Electronic_MadeAppts            SeekCan.
            Electronic_TrackedHealthCosts   SeekCan.
            Electronic_CompletedForms       SeekCan.
            Electronic_TestResults          SeekCan.
            HaveDevice_Tablet               HaveDev.
            HaveDevice_SmartPh              HaveDev.
            HaveDevice_CellPh               HaveDev.
            TabletHealthWellnessApps        TabletH.
            Tablet_AchieveGoal              Tablet_.
            Tablet_MakeDecision             Tablet_.
            Tablet_DiscussionsHCP           Tablet_.
            OtherDevTrackHealth             SeekCan.
            SharedHealthDeviceInfo          SharedH.
            IntRsn_VisitedSocNet            SeekCan.
            IntRsn_SharedSocNet             SeekCan.
            IntRsn_WroteBlog                SeekCan.
            IntRsn_SupportGroup             SeekCan.
            IntRsn_YouTube                  SeekCan.
            TextFromDoctor                  TextFro.
            RegularProvider                 SeekCan.
            MostRecentCheckup2              MostRec.
            FreqGoProvider                  FreqGoP.
            ChanceAskQuestions              ChanceA.
            FeelingsAddressed               ChanceA.
            InvolvedDecisions               ChanceA.
            UnderstoodNextSteps             ChanceA.
            ExplainedClearly                ChanceA.
            SpentEnoughTime                 ChanceA.
            HelpUncertainty                 ChanceA.
            QualityCare                     Quality.
            ProbCare_BringTest              ProbCar.
            ProbCare_WaitLong               ProbCar.
            ProbCare_RedoTest               ProbCar.
            ProbCare_ProvideHist            ProbCar.
            HealthIns_InsuranceEmp          SeekCan.
            HealthIns_InsurancePriv         SeekCan.
            HealthIns_Medicare              SeekCan.
            HealthIns_Medicaid              SeekCan.
            HealthIns_Tricare               SeekCan.
            HealthIns_VA                    SeekCan.
            HealthIns_IHS                   SeekCan.
            HealthIns_Other                 HealthF.
            HealthIns_Other_OS              HealthI.
            HealthInsurance                 SeekCan.
            ProviderMaintainEMR2            TextFro.
            OfferedAccessHCP2               TextFro.
            OfferedAccessInsurer2           TextFro.
            HCPEncourageOnlineRec           SeekCan.
            AccessOnlineRecord              AccessO.
            NotAccessed_SpeakDirectly       NotAcce.
            NotAccessed_NoInternet          NotAcce.
            NotAccessed_NoNeed              NotAcce.
            NotAccessed_ConcernedPrivacy    NotAcce.
            NotAccessed_NoRecord            NotAcce.
            NotAccessed_Other               NotAccF.
            NotAccessed_Other_OS            $NotAccG.
            RecordsOnline_Labs              RecordF.
            RecordsOnline_Meds              RecordF.
            RecordsOnline_HealthProbs       RecordF.
            RecordsOnline_Allergies         RecordF.
            RecordsOnline_VisitSummary      RecordF.
            RecordsOnline_ClinNotes         RecordF.
            RecordsOnline_Immunizations     RecordF.
            RecordsOnline_MakeAppt          Records.
            RecordsOnline_RefillMeds        Records.
            RecordsOnline_Paperwork         Records.
            RecordsOnline_RequestCorrection Records.
            RecordsOnline_MessageHCP        Records.
            RecordsOnline_ViewResults       Records.
            RecordsOnline_MonitorHealth     Records.
            RecordsOnline_DownloadHealth    Records.
            RecordsOnline_AddHealthInfo     Records.
            RecordsOnline_MakeDecision      Records.
            ESent_AnotherHCP                Records.
            ESent_Family                    Records.
            ESent_HealthApp                 Records.
            UnderstandOnlineMedRec          Underst.
            UsefulOnlineMedRec              UsefulO.
            ConfidentInfoSafe               Confide.
            WithheldInfoPrivacy             SeekCan.
            ElectInfoSafe                   ElectIn.
            AccessFamilyMedRec              AccessF.
            AccessedFamRec_TheirPwd         Accesse.
            AccessedFamRec_MyPwd            Accesse.
            Caregiving_Child                CaregiJ.
            Caregiving_Spouse               CaregiJ.
            Caregiving_Parent               CaregiJ.
            Caregiving_Family               CaregiJ.
            Caregiving_Friend               CaregiJ.
            Caregiving_No                   CaregiK.
            CaregivingWho_Cat               CaregiL.
            Caregiving_Cancer               Caregiv.
            Caregiving_Alzheimers           Caregiv.
            Caregiving_OrthoMusc            Caregiv.
            Caregiving_MentalHealth         Caregiv.
            Caregiving_ChronicCond          Caregiv.
            Caregiving_NeuroDev             Caregiv.
            Caregiving_AcuteCond            Caregiv.
            Caregiving_Aging                Caregiv.
            Caregiving_NotSure              Caregiv.
            Caregiving_Other                CaregiF.
            Caregiving_Other_OS             $CaregiI.
            CaregivingCond_Cat              CaregiH.
            Caregiving_HoursPerWeek         CaregiG.
            HeardDNATest                    HeardDN.
            GeneticTestUse_DetermineRisk    Genetic.
            GeneticTestUse_DetermineTx      Genetic.
            GeneticTestUse_DetermineMed     Genetic.
            GeneticTestUse_DeterminePass    Genetic.
            GeneticTestUse_Cat              GenetiF.
            HadTest_Paternity               Genetic.
            HadTest_Ancestry                Genetic.
            HadTest_DNAFing                 Genetic.
            HadTest_CFCarrier               Genetic.
            HadTest_BRCA                    Genetic.
            HadTest_Lynch                   Genetic.
            HadTest_None                    Genetic.
            HadTest_NotSure                 Genetic.
            HadTest_Other                   HadTest.
            HadTest_Other_OS                $HadTesG.
            HadTest_Cat                     HadTesF.
            GeneralHealth                   General.
            OwnAbilityTakeCareHealth        ConfidF.
            MedConditions_Diabetes          SeekCan.
            MedConditions_HighBP            SeekCan.
            MedConditions_HeartCondition    SeekCan.
            MedConditions_LungDisease       SeekCan.
            MedConditions_Arthritis         SeekCan.
            MedConditions_Depression        SeekCan.
            Height_Feet                     HeightF.
            Height_Inches                   Height_.
            Weight                           Weight.
            LittleInterest                  LittleI.
            Hopeless                        LittleI.
            Nervous                         LittleI.
            Worrying                        LittleI.
            EmotionalSupport                SeekCan.
            TalkHealthFriends               SeekCan.
            HelpDailyChores                 SeekCan.
            Deaf                            SeekCan.
            UseMenuCalorieInfo              UseMenu.
            Fruit                             Fruit.
            Vegetables                        Fruit.
            AlcoholConditions_Cancer        Alcohol.
            AlcoholConditions_HeartDisease  Alcohol.
            AlcoholConditions_Diabetes      Alcohol.
            AlcoholConditions_Cholesterol   Alcohol.
            AlcoholConditions_LiverDisease  Alcohol.
            AlcoholConditions_Overweight    Alcohol.
            AlcoholIncreaseCancer           AlcohoF.
            AlcoholReduceHeart              AlcohoF.
            TimesModerateExercise           TimesMo.
            HowLongModerateExerciseMn       HowLonF.
            HowLongModerateExerciseHr       HowLong.
            TimesStrengthTraining           TimesSt.
            TanningBed                      Tanning.
            SkinCancerHPExam                SkinCaF.
            SkinCancerSelfCheck             SkinCan.
            Smoke100                        Smoke1F.
            SmokeNow                        SmokeNo.
            TriedQuit                       TriedQu.
            ConsiderQuit                    TriedQu.
            ElectCigLessHarm                ElectCi.
            UsedECigEver                    UsedECi.
            UseECigNow                      UseECig.
            DrTalkLungTest                  Alcohol.
            SmokelessLessHarm               Smokele.
            HookahLessHarm                  HookahL.
            GenderC                         GenderC.
            WhenPapTest                     WhenPap.
            WhenMammogram                   WhenMam.
            EverHadPSATest                  EverHad.
            HeardHPV                        HeardHP.
            HPVCauseCancer_Cervical         HPVCaus.
            HPVCauseCancer_Penile           HPVCaus.
            HPVCauseCancer_Anal             HPVCaus.
            HPVCauseCancer_Oral             HPVCaus.
            HPVSTD                           HPVSTD.
            HPVMedicalTreatment             HPVMedi.
            HeardHPVVaccine2                SeekCan.
            HPVShotPrevent                  HPVShot.
            FamBetween9and27                FamBetw.
            DiscussHPVVaccination12m        Discuss.
            RecommendHPVShot                Discuss.
            EverHadCancer                   EverHaF.
            CaBladder                       CaBladd.
            CaBone                          CaBladd.
            CaBreast                        CaBladd.
            CaCervical                      CaBladd.
            CaColon                         CaBladd.
            CaEndometrial                   CaBladd.
            CaHeadNeck                      CaBladd.
            CaHodgkins                      CaBladd.
            CaLeukemia                      CaBladd.
            CaLiver                         CaBladd.
            CaLung                          CaBladd.
            CaMelanoma                      CaBladd.
            CaNonHodgkin                    CaBladd.
            CaOral                          CaBladd.
            CaOvarian                       CaBladd.
            CaPancreatic                    CaBladd.
            CaPharyngeal                    CaBladd.
            CaProstate                      CaBladd.
            CaRectal                        CaBladd.
            CaRenal                         CaBladd.
            CaSkin                          CaBladd.
            CaStomach                       CaBladd.
            CaOther                         CaOther.
            CaOther_OS                      $CaOtheF.
            Cancer_Cat                      Cancer_.
            WhenDiagnosedCancer             WhenDia.
            UndergoCancerTreatment          Undergo.
            CancerTx_Chemo                  CancerT.
            CancerTx_Radiation              CancerT.
            CancerTx_Surgery                CancerT.
            CancerTx_Other                  CancerT.
            HowLongFinishTreatment_Cat      HowLonH.
            CancerTxSummary                 CancerF.
            CancerDeniedCoverage            CancerD.
            CancerHurtFinances              CancerH.
            CancerAbilityToWork             CancerA.
            ClinicalTrialCancerTx           Clinica.
            DiscussedClinicalTrial          DiscusF.
            ChanceGetCancer                 ChanceG.
            EverythingCauseCancer           AlcohoF.
            PreventNotPossible              AlcohoF.
            TooManyRecommendations          AlcohoF.
            CancerMoreCommon                AlcohoF.
            CancerFatal                     AlcohoF.
            RatherNotKnowChance             AlcohoF.
            FreqWorryCancer                 FreqWor.
            FamilyEverHadCancer             FamilyE.
            Age                                 Age.
            OccupationStatus                OccupaF.
            OccupationStatus_OS             $Occupat.
            Employed                        Employe.
            Unemployed                      Employe.
            Homemaker                       Employe.
            Student                         Employe.
            Retired                         Employe.
            Disabled                        Employe.
            OtherOcc                        Employe.
            MultiOcc                        MultiOc.
            ActiveDutyArmedForces           ActiveD.
            ReceivedCareVA                  Receive.
            MaritalStatus                   Marital.
            Education                       Educati.
            BornInUSA                       BornInU.
            YearCameToUSA                   YearCam.
            SpeakEnglish                    SpeakEn.
            NotHisp                         NotHisp.
            Mexican                         NotHisp.
            PuertoRican                     NotHisp.
            Cuban                           NotHisp.
            OthHisp                         NotHisp.
            Hisp_Cat                        Hisp_Ca.
            White                             White.
            Black                             White.
            AmerInd                           White.
            AsInd                             White.
            Chinese                           White.
            Filipino                          White.
            Japanese                          White.
            Korean                            White.
            Vietnamese                        White.
            OthAsian                          White.
            Hawaiian                          White.
            Guamanian                         White.
            Samoan                            White.
            OthPacIsl                         White.
            Race_Cat2                       Race_Ca.
            SexualOrientation               SexualF.
            SexualOrientation_OS            $SexualO.
            TotalHousehold                  TotalHo.
            R_HHAdults                      R_HHAdul.
            HHAdults_Num                    HHAdults.
            SelfGender                      SelfGen.
            SelfAge                         SelfAge.
            SelfMOB                         SelfMOB.
            HHAdultGender2                  HHAdulM.
            HHAdultAge2                     HHAdult.
            HHAdultMOB2                     HHAdulI.
            HHAdultGender3                  HHAdulN.
            HHAdultAge3                     HHAdulF.
            HHAdultMOB3                     HHAdulJ.
            HHAdultGender4                  HHAdulO.
            HHAdultAge4                     HHAdulG.
            HHAdultMOB4                     HHAdulK.
            HHAdultGender5                  HHAdulP.
            HHAdultAge5                     HHAdulH.
            HHAdultMOB5                     HHAdulL.
            ChildrenInHH                    Childre.
            RentOrOwn                       RentOrO.
            CellPhone                       HaveDev.
            PhoneInHome                     HaveDev.
            IncomeRanges                    IncomeR.
            MailSurveyTime_Min              MailSuF.
            MailSurveyTime_Hrs              MailSur.
            TypeOfAddressA                  TypeOfA.
            TypeOfAddressB                  TypeOfA.
            TypeOfAddressC                  TypeOfA.
            TypeOfAddressD                  TypeOfA.
			AgeGrpA 						AgeGrpA.
			AgeGrpB 						AgeGrpB.
			EducA 							EducA.
			EducB							EducB.
			RaceEthn 						RaceEthn.
			HHInc 							HHInc.
			BMI 							BMI.
			AgeDX 							AgeDX.
			TimeSinceDX 					TimeSinceDX.
			smokeStat 						smokeStat.
			RaceEthn5 						RaceEthn5f.
			phq4 							phq4f.
			WeeklyMinutesModerateExercise  	WeeklyMinutesModerateExercise.
            IncomeRanges_IMP  				incomer.
			ECigUse 						ECigStat.

        ;
run;
